config/routes.rb
Rails.application.routes.draw do

  resources :media_collections do
    collection do
      get 'availables'
    end
  end

  get 'get_image/:id(/:version)' => 'media_collections#get_image'

  devise_for :users

  root 'media_collections#availables'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)

    case user.role
      when 'admin'
        can :manage, :all

      when 'author'
        can [:index, :availables], MediaCollection
        can [:edit, :update, :create, :destroy], MediaCollection, user_id: user.id

        can :show, MediaCollection do |media_collection|

          # Если медиа коллекция открыта (0 - закрыта | 1 - открыта)
          # и этой коллекция другого пользователя
          if media_collection.available == 0 and media_collection.user_id != user.id
            false
          else
            true
          end

        end


      else
        can :availables, MediaCollection
        can :show, MediaCollection do |media_collection|

          true if media_collection.available == 1

        end
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/image.rb
class Image < ActiveRecord::Base

  belongs_to :media_collection
  mount_uploader :image, ImageUploader

end

app/models/media_collection.rb
class MediaCollection < ActiveRecord::Base

  belongs_to :user
  has_many :images, dependent: :destroy
  has_many :urls, dependent: :destroy

  accepts_nested_attributes_for :images, :reject_if => :all_blank, allow_destroy: true
  accepts_nested_attributes_for :urls, :reject_if => :all_blank, allow_destroy: true

  # Доступность коллекции
  AVAILABLE = [
      [ 'Только мне', 0 ],
      [ 'Всем', 1 ]
  ]

  validates :user_id, :name, :available, presence: true
  validates :available, inclusion: { in: AVAILABLE.map{ |k,v| v } }

end

app/models/url.rb
class Url < ActiveRecord::Base

  belongs_to :media_collection

  validates :url, url: { message: 'не верна' }

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :media_collections

  before_create :set_default_role

  private

  # Назначанем роль по умолчанию
  # Вего две роли author и admin
  def set_default_role
    self.role = 'author'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_out_path_for(resource)
    availables_media_collections_path
  end

  def after_sign_in_path_for(resource)
    media_collections_path
  end

  def after_sign_up_path_for(resource)
    media_collections_path
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

end

app/controllers/media_collections_controller.rb
class MediaCollectionsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :get_image, :availables]

  def availables
    authorize! :availables, MediaCollection
    @media_collections = MediaCollection.where(available: 1).decorate
  end


  # GET /media_collections
  # GET /media_collections.json
  def index
    authorize! :index, MediaCollection
    @media_collections = current_user.media_collections.decorate
  end

  # GET /media_collections/1
  # GET /media_collections/1.json
  def show
    @media_collection = MediaCollection.find(params[:id]).decorate
    authorize! :show, @media_collection
  end

  # GET /media_collections/new
  def new
    @media_collection = MediaCollection.new
    @media_collection.images.build
    @media_collection.urls.build
  end

  # GET /media_collections/1/edit
  def edit
    @media_collection = MediaCollection.find(params[:id]).decorate
    authorize! :edit, @media_collection
  end

  # POST /media_collections
  # POST /media_collections.json
  def create
    @media_collection = MediaCollection.new(media_collection_params)
    @media_collection.user_id = current_user.id

    respond_to do |format|
      if @media_collection.save
        format.html { redirect_to @media_collection, notice: 'Медиа коллекция успешно создана.' }
        format.json { render :show, status: :created, location: @media_collection }
      else
        format.html { render :new }
        format.json { render json: @media_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media_collections/1
  # PATCH/PUT /media_collections/1.json
  def update
    @media_collection = MediaCollection.find(params[:id])
    authorize! :update, @media_collection

    respond_to do |format|
      if @media_collection.update(media_collection_params)
        format.html { redirect_to @media_collection, notice: 'Медиа коллекция успешно обновлена.' }
        format.json { render :show, status: :ok, location: @media_collection }
      else
        format.html { render :edit }
        format.json { render json: @media_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media_collections/1
  # DELETE /media_collections/1.json
  def destroy
    @media_collection = MediaCollection.find(params[:id])
    @media_collection.destroy

    authorize! :destroy, @media_collection

    respond_to do |format|
      format.html { redirect_to media_collections_url, notice: 'Медиа коллекция успешно удалена.' }
      format.json { head :no_content }
    end
  end

  def get_image

    image = Image.find(params[:id])

    if params[:version]
      image_url = File.join('public', image.image.send(params[:version]).url)
    else
      image_url = File.join('public', image.image.url)
    end


    @media_collection = image.media_collection

    if can? :show, @media_collection

      if File.exist? image_url

        send_file image_url, type: image.image.content_type, disposition: 'inline'
      else

        render text: "Нет доступа или файл не найден. #{image_url}", :status => 404
      end

    else
      render text: 'Нет доступа или файл не найден.', :status => 404
    end

  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def media_collection_params
      params.require(:media_collection).permit(:user_id, :name, :available,
                                               images_attributes: [:image, :name, :media_collection_id, :id, :_destroy],
                                               urls_attributes: [:name, :url, :media_collection_id, :id, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_add_fields(name, f, association)

    new_object = f.object.send(association).klass.new
    id = new_object.object_id

    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end

    link_to '#add_field', class: 'btn btn-default pull-right btn-block add_fields', data: {id: id, fields: fields.gsub("\n", "")} do
      content_tag(:i, '', class: 'fa fa-plus-circle') + " " + name
    end

  end

end

app/helpers/images_helper.rb
module ImagesHelper

  def safely_url id, version = false

    if version
      File.join('/get_image', id.to_s, version )
    else
      File.join('/get_image', id.to_s )
    end

  end

end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Медиа коллекции | тестовый проект"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

    / Галлерея
    %link{:href => "//blueimp.github.io/Gallery/css/blueimp-gallery.min.css", :rel => "stylesheet"}
    %script{:src => "//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"}


  %body

    = yield 'body'

    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar

        .collapse.navbar-collapse#bs-example-navbar-collapse-1
          %ul.nav.navbar-nav
            %li{ class: (action_name == 'index') ? 'active' : nil }
              - if user_signed_in?
                %a{:href => media_collections_path} Мои коллекции
            %li{ class: (action_name == 'availables') ? 'active' : nil }
              %a.active{:href => "/"} Общедоступные коллекции

          .navbar-collapse.collapse.navbar-responsive-collapse

            %ul.nav.navbar-nav.navbar-right
              - if user_signed_in?
                %li
                  %p.navbar-text
                    Вы вошли как:
                    = current_user.email
                %li
                  = link_to "Выйти", "/users/sign_out", method: :delete
              - else
                %li= link_to "Войти", "/users/sign_in"
                %li= link_to "Зарегистрироваться", "/users/sign_up"
    .container
      .row
        .col-lg-8
          = bootstrap_flash
          = yield
        .col-lg-4
          = yield 'operations'
      %footer
        %br
        %hr
        %p.text-muted
          Медиа коллекции - тестовый проект
          %br
          %br
          Разработчик: Стержаков Игорь Валерьевич
          %br
          Телефон: 8 (916) 247-40-55
          %br
          Email:
          %a.text-warning{ href: 'mailto:sterjakov@bk.ru'}
            sterjakov@bk.ru
        %br

app/views/media_collections/_form.html.haml
= form_for(@media_collection, html: { multipart: true }) do |f|

  = render partial: 'errors/index', locals: { model: @media_collection }

  .field
    = f.label :name, 'Название коллекции'
    %br/
    = f.text_field :name, class: 'form-control'
  .field
    = f.label :available, 'Кому будет доступна коллекция?'
    %br/
    = f.select :available, MediaCollection::AVAILABLE, {}, class: 'form-control'

  %br

  %div{:role => "tabpanel"}
    / Nav tabs
    %ul.nav.nav-tabs{:role => "tablist"}
      %li.active{:role => "presentation"}
        %a{"aria-controls" => "home", "data-toggle" => "tab", :href => "#photos", :role => "tab"} Мои фотографии
      %li{:role => "presentation"}
        %a{"aria-controls" => "profile", "data-toggle" => "tab", :href => "#links", :role => "tab"} Мои ссылки
    / Tab panes
    .tab-content
      #photos.tab-pane.active{:role => "tabpanel"}

        %br

        = f.fields_for :images do |builder, image|

          = render 'image_fields', f: builder

        = link_to_add_fields "Добавить фотографию", f, :images
        .clearfix

        %hr

      #links.tab-pane{:role => "tabpanel"}

        %br

        = f.fields_for :urls do |builder|

          = render 'url_fields', f: builder

        = link_to_add_fields "Добавить ссылку", f, :urls
        .clearfix

        %hr







  .actions
    = f.submit class: 'btn btn-success btn-lg', value: 'Сохранить коллекцию!'

  %br

app/views/media_collections/_image_fields.html.haml
.well

  .field
    = f.label :name, 'Название фотографии'
    %br/
    = f.text_field :name, class: 'form-control'

  .field
    = f.label :image, 'Фотография'
    %br/
    .pull-left
      = f.file_field :image
    .pull-right
      %a.btn.btn-danger.btn-xs.remove_field{ href: '#remove_field' }
        Удалить
      = f.hidden_field :_destroy, class: 'for_remove'
    .clearfix

  %br

  - if f.object.id.present?
    = image_tag safely_url(f.object.id), style: 'max-width: 100%;'

app/views/media_collections/_url_fields.html.haml
.well

  .col-lg-4

    .field
      = f.label :name, 'Название'
      %br/
      = f.text_field :name, class: 'form-control'

  .col-lg-6

    .field
      = f.label :url, 'Адрес'
      %br/
      = f.text_field :url, class: 'form-control'

  .col-lg-2
    %a.btn.btn-danger.btn-xs.remove_field{ href: '#remove_field', style: 'margin-top: 40px;' }
      Удалить
    = f.hidden_field :_destroy, class: 'for_remove'
  .clearfix

app/views/media_collections/availables.html.haml
- content_for 'operations' do
  .well.sidebar-nav
    %ul.nav.nav-pills.nav-stacked
      %li.nav-header.text-muted Меню:
      %br
      = link_to new_media_collection_path, class: 'btn btn-primary btn-lg btn-block' do
        %i.fa.fa-plus-circle
        Создать новую коллекцию



%h1 Все общедоступные коллекции

- if @media_collections.count > 0

  %table.table.table-striped
    %thead
      %tr
        %th Название
        %th Автор
        %th.text-right
    %tbody
      - @media_collections.each do |media_collection|
        %tr
          %td
            = link_to media_collection.name, media_collection_path(media_collection)
          %td= media_collection.user.email
          %td.text-right
            = link_to 'Смотреть', media_collection_path(media_collection), class: 'btn btn-xs btn-default'
            = link_to 'Править', edit_media_collection_path(media_collection), class: 'btn btn-xs btn-default'
            = link_to 'Удалить', media_collection, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger'
  %br/

- else

  %p.text-muted
    Пока что у вас нет ни одной медиа коллекции.

app/views/media_collections/edit.html.haml
- content_for 'operations' do
  .well.sidebar-nav
    %ul.nav.nav-pills.nav-stacked
      %li.nav-header.text-muted Меню:
      %br
      = link_to media_collection_path(@media_collection), class: 'btn btn-default btn-lg btn-block' do
        %i.fa.fa-eye
        Смотреть
      = link_to media_collections_path, class: 'btn btn-default btn-lg btn-block' do
        %i.fa.fa-arrow-left
        Назад


%h1 Редактирование коллекции
= render 'form'

app/views/media_collections/index.html.haml
- content_for 'operations' do
  .well.sidebar-nav
    %ul.nav.nav-pills.nav-stacked
      %li.nav-header.text-muted Меню:
      %br
      = link_to new_media_collection_path, class: 'btn btn-primary btn-lg btn-block' do
        %i.fa.fa-plus-circle
        Создать новую коллекцию



%h1 Мои медиа коллекции

- if @media_collections.count > 0

  %table.table.table-striped
    %thead
      %tr
        %th Название
        %th Доступно
        %th.text-right
    %tbody
      - @media_collections.each do |media_collection|
        %tr
          %td
            = link_to media_collection.name, media_collection_path(media_collection)
          %td= media_collection.available_human
          %td.text-right
            = link_to 'Смотреть', media_collection_path(media_collection), class: 'btn btn-xs btn-default'
            = link_to 'Править', edit_media_collection_path(media_collection), class: 'btn btn-xs btn-default'
            = link_to 'Удалить', media_collection, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger'
  %br/

- else

  %p.text-muted
    Пока что у вас нет ни одной медиа коллекции.

app/views/media_collections/new.html.haml
- content_for 'operations' do
  .well.sidebar-nav
    %ul.nav.nav-pills.nav-stacked
      %li.nav-header.text-muted Меню:
      %br
      = link_to media_collections_path, class: 'btn btn-default btn-lg btn-block' do
        %i.fa.fa-arrow-left
        Назад

%h1 Создание новой коллекции
= render 'form'

app/views/media_collections/show.html.haml
- if can? :edit, @media_collection

  - content_for 'operations' do
    .well.sidebar-nav
      %ul.nav.nav-pills.nav-stacked
        %li.nav-header.text-muted Меню:
        %br
        = link_to edit_media_collection_path(@media_collection), class: 'btn btn-warning btn-lg btn-block' do
          %i.fa.fa-pencil
          Редактировать
        = link_to media_collections_path, class: 'btn btn-default btn-lg btn-block' do
          %i.fa.fa-arrow-left
          Назад

- content_for 'body' do

  / The Bootstrap Image Gallery lightbox, should be a child element of the document body
  #blueimp-gallery.blueimp-gallery
    / The container for the modal slides
    .slides
    / Controls for the borderless lightbox
    %h3.title
    %a.prev ‹
    %a.next ›
    %a.close ×
    %a.play-pause
    %ol.indicator
    / The modal dialog, which will be used to wrap the lightbox content
    .modal.fade
      .modal-dialog
        .modal-content
          .modal-header
            %button.close{"aria-hidden" => "true", :type => "button"} &times;
            %h4.modal-title
          .modal-body.next
          .modal-footer
            %button.btn.btn-default.pull-left.prev{:type => "button"}
              %i.glyphicon.glyphicon-chevron-left
              Назад
            %button.btn.btn-primary.next{:type => "button"}
              Вперед
              %i.glyphicon.glyphicon-chevron-right



%h1
  = @media_collection.name
%p
  - if @media_collection.available > 0
    Эта коллекция доступна всем по этому адресу:
    %a{ href: request.original_url }
      = request.original_url
  - else
    Эта коллекция доступна только вам.

%p.text-muted
  %strong Автор:
  = @media_collection.user.email

%br
  %div{:role => "tabpanel"}
    / Nav tabs
    %ul.nav.nav-tabs{:role => "tablist"}
      %li.active{:role => "presentation"}
        %a{"aria-controls" => "home", "data-toggle" => "tab", :href => "#photos", :role => "tab"} Мои фотографии
      %li{:role => "presentation"}
        %a{"aria-controls" => "profile", "data-toggle" => "tab", :href => "#links", :role => "tab"} Мои ссылки
    / Tab panes
    .tab-content
      #photos.tab-pane.active{:role => "tabpanel"}

        %br


        - @media_collection.images.each do |image|

          %a.gallery-1{ "data-gallery" => "gallery-1", href: safely_url(image.id), rel: 'group-1' }
            = image_tag safely_url(image.id, 'thumb')

        %hr

      #links.tab-pane{:role => "tabpanel"}

        %br


        - @media_collection.urls.each do |url|

          %blockquote
            %a.lead{ href: url.url, target: '_blank' }
              = url.url
            %small
              = url.name

            .clearfix


        %hr